[project]
name = "os-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apscheduler>=3.11.0",
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "openai>=2.6.1",
    "python-dotenv>=1.2.1",
    "reportlab>=4.4.4",
]
